### PR TITLE
[ AMSD-51 ] Implemented the passengers employees maintenance and feedback services and controllers

### PR DESCRIPTION
**Pull request by Gentrit851**
The service layer was added using the Repository dependencies for basic CRUD operations. The controllers exposed the endpoints for the different entities using the service layer dependencies.

### CODE REVIEW

**Review by ArdiZariqi — APPROVED** [review]
Well done!

**Review by ArianitSGashi — APPROVED** [review]
Nice job!

**Review by ArditGjyrevci — APPROVED** [review]
Good Job!

**Review by floriansaqipi — APPROVED** [review]
Nice job!

**Pull request merged**
