### PR TITLE
[ AMSD-100 ] Fix the FlightMapper bug

### PR DESCRIPTION
**Pull request by ArdiZariqi**
The airport IDs have been added to the FlightMapper and fixed the json serialization problem.

### CODE REVIEW

**Review by ArianitSGashi — APPROVED** [review]
Good job!

**Review by floriansaqipi — APPROVED** [review]
Nicely done!

**Review by Gentrit851 — APPROVED** [review]
Good Job !

**Review by ArditGjyrevci — APPROVED** [review]
Nice job!

**Pull request merged**
