### PR TITLE
[ AMSD-50 ] Implement the airports airlines aircraft flights services and controllers

### PR DESCRIPTION
**Pull request by ArdiZariqi**
The service layer have been added using the Repository dependencies for basic CRUD operations. The controllers have exposed the endpoints for the different entities using the service layer dependencies.

### CODE REVIEW

**Review by Gentrit851 — APPROVED** [review]
Nice Job !

**Review by ArditGjyrevci — APPROVED** [review]
Good job my friend!

**Review by ArianitSGashi — APPROVED** [review]
Well done!

**Review by floriansaqipi — APPROVED** [review]
Nicely done!

**Pull request merged**
