### PR TITLE
[ AMSD-28 ] Created check_in gate_assignments flight_schedules flight_crews tables

### PR DESCRIPTION
**Pull request by ArianitSGashi**
The check_in, gate_assignments, flight_schedules and flight_crews table data models have been migrated.

### CODE REVIEW

**Review by ArditGjyrevci — APPROVED** [review]

**Review by ArdiZariqi — APPROVED** [review]
Nicely done!

**Review by floriansaqipi — APPROVED** [review]
Nicely done!

**Review by Gentrit851 — APPROVED** [review]
Good Job !

**Comment by floriansaqipi** [comment]
Nicely done all the tables are now present.

**Pull request merged**
