### PR TITLE
[ AMSD-53 ] Document the progress made on the read.me file

### PR DESCRIPTION
**Pull request by Gentrit851**
The progress made so far has been documented. The database model has been documented. The entities have been mentioned with their annotations. The JPA implementation. The controller layer that accepts the requests.

### CODE REVIEW

**Review by ArdiZariqi — APPROVED** [review]
Well done!

**Review by ArianitSGashi — APPROVED** [review]
Nice job!

**Review by ArditGjyrevci — APPROVED** [review]
Good Job!

**Review by floriansaqipi — APPROVED** [review]
The read.me looks nice!

**Pull request merged**
