### PR TITLE
[ AMSD-38 ] Updated relationship annotations

### PR DESCRIPTION
**Pull request by Gentrit851**
The relationships of the passengers, employess, maintenance, feedback have been updated.

### CODE REVIEW

**Review by ArditGjyrevci — APPROVED** [review]
Nicely done!

**Review by floriansaqipi — APPROVED** [review]
Nicely done!

**Review by ArdiZariqi — APPROVED** [review]
Nice job!

**Review by ArianitSGashi — APPROVED** [review]
Well done!

**Pull request merged**
