### PR TITLE
[ AMSD-54 ] Push current iteration to the main branch

### PR DESCRIPTION
**Pull request by ArditGjyrevci**
This current iteration has basic CRUD operations on the exposed endpoints. We can perform these operations on about twenty endpoints. ORM have been integrated, the service and controller layer, also.

### CODE REVIEW

**Review by ArdiZariqi — APPROVED** [review]
Well done!

**Review by ArianitSGashi — APPROVED** [review]
Nice job!

**Review by floriansaqipi — APPROVED** [review]
The application has a very functional REST API now.

**Review by Gentrit851 — APPROVED** [review]
Nice Job !

**Pull request merged**
