### PR TITLE
[ AMSD-48 ] Implement the check_in gate_assignments flight_schedules and flight_crews services and controllers

### PR DESCRIPTION
**Pull request by ArianitSGashi**
The service layer have been added using the Repository dependencies for basic CRUD operations. The controllers  have exposed the endpoints for the different entities using the service layer dependencies.

### CODE REVIEW

**Review by floriansaqipi — APPROVED** [review]
Nicely done!

**Review by ArditGjyrevci — APPROVED** [review]
Great Job!

**Review by ArdiZariqi — APPROVED** [review]
Nice job!

**Review by Gentrit851 — APPROVED** [review]
Nice Job !

**Pull request merged**
