### PR TITLE
[ AMSD-58 ] Implement the airports airlines aircraft flights dtos and mapping

### PR DESCRIPTION
**Pull request by ArdiZariqi**
The DTOs needed for the CRUD operations have been added for these entities. Also, the Mapper to entities.

### CODE REVIEW

**Review by floriansaqipi — APPROVED** [review]
Nicely Done! Change the PR title to Uppercase (the jira task id).

**Review by ArditGjyrevci — APPROVED** [review]

**Comment by ArdiZariqi** [comment]
> Nicely Done! Change the PR title to Uppercase (the jira task id).

The PR title is in Uppercase, look carefully.

**Comment by floriansaqipi** [comment]
It is after you changed it! Nice!

**Comment by floriansaqipi** [comment]
It is now after you've changed it. Nice! Don't delete the comments. Unless you want to open the PR again.

**Pull request merged**
